### ISSUE TITLE
error when I try to install the dependencies of my project

### ISSUE THREAD

**Issue by robertomsen** [uidb-dev/react.cordova#35]
When I try to install the dependencies of a project that was already working (previously), I get the following error:

![image](https://user-images.githubusercontent.com/34248284/176288689-bd11a83b-cae0-47ae-8283-7801d06fa770.png)

Any idea how to fix it?

**Comment by orchuban** [comment]
If the CLI installed the project (you have to see package.json on the new folder), then try:
`npm i --legacy-peer-deps`
or `npm i cordova_script`

if it's work, run `npm run build`

**Comment by robertomsen** [comment]
Hi @orchuban,

I have found the solution to the problem, I expose it here to help the project, and to solve problems in the future, to someone who may have them:

The problem is in the version of node.js, curiously, from version 15, this error appears, but if you install the latest LTS of node in its version 14, this will not happen, and you will be able to do npm install normally.

I hope it helps someone!

All the best.

**Comment by orchuban** [comment]
Thank you @robertomsen

**Comment by bslikkerveer** [comment]
Just additional confirmation; Experienced the same (running current node lts 16), force installing with --legacy-peer-deps made it work.

**Comment by malutanpetronel** [comment]
it happen for me with node v14.18.0

**Comment by orchuban** [comment]
Thanks for the detailed report, and sorry this sat so long. This turned out to be the same root cause as #40, and it's **fixed in [2.6.0](https://www.npmjs.com/package/react.cordova), published today.**

What was happening: `create-react-app` installs React 19, but `cordova_script` and `navigation-controller` declared `react@^18.2.0` as a peer dependency, so `npm install` failed with ERESOLVE. The `--legacy-peer-deps` workaround gets you past that, but it makes npm ignore peer ranges while hoisting, which is what later produces the `Cannot find module 'ajv/dist/compile/codegen'` failure in #40.

`reco init` now pins React 18 — what those packages actually support — and writes an `.npmrc` with `legacy-peer-deps=false`, so no workaround is needed.

One correction to the thread: the Node 15+ theory was a red herring. That was the OpenSSL `digital envelope routines::unsupported` error, which is a different problem entirely.
